openapi: 3.0.0
info:
  title: URL Shortener API
  description: Service simple de réduction d'URL.
  version: v2
servers:
  - url: http://localhost:8080/api-v2
    description: API V2 (JSON)
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
paths:
  /:
    get:
      summary: Get link count
      responses:
        '200':
          description: Nombre de liens créés.
          content:
            application/json:
              schema:
                type: object
                properties:
                  nb_links:
                    type: integer
                    example: 4
    post:
      summary: Create a short link
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  format: url
                  example: https://perdu.com
      responses:
        '201':
          description: Lien créé
          content:
            application/json:
              schema:
                type: object
                properties:
                  short_url:
                    type: string
                    example: https://localhost:8080/api-v2/abc123
                  long_url:
                    type: string
                    example: https://perdu.com
                  created_at:
                    type: string
                    format: date-time
                  idLink:
                    type: integer
                  secret:
                    type: string
                    example: RatQak
  /{url}:
    get:
      summary: Redirige vers l'URL longue et incrémente le compteur de visites (HTML) ou retourne les infos du lien (JSON)
      parameters:
        - name: url
          in: path
          required: true
          schema:
            type: string
      responses:
        '302':
          description: Redirection vers l'URL longue (HTML)
        '200':
          description: Informations sur le lien (JSON)
          content:
            application/json:
              schema:
                type: object
                properties:
                  short_url:
                    type: string
                  long_url:
                    type: string
                  visit:
                    type: integer
        '404':
          description: Lien non trouvé
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    delete:
      summary: Supprime un lien raccourci (nécessite la clé secrète)
      security:
        - ApiKeyAuth: []
      parameters:
        - name: url
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Lien supprimé
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Lien supprimé
        '401':
          description: Clé API manquante
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Clé API manquante
        '403':
          description: Clé API incorrecte
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Clé API incorrecte
        '404':
          description: Lien non trouvé
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Lien non trouvé