openapi: 3.0.0
info:
  title: URL Shortener API
  description: Service simple de réduction d'URL.
  version: v1
servers:
  - url: http://localhost:8080/api-v1
    description: API V1 (JSON)
paths:
  /:
    get:
      summary: Get link count
      responses:
        '200':
          description: Nombre de liens créés.
          content:
            application/json:
              schema:
                type: object
                properties:
                  nb_links:
                    type: integer
                    example: 4
    post:
      summary: Create a short link
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  format: url
                  example: https://perdu.com
      responses:
        '201':
          description: Lien créé
          content:
            application/json:
              schema:
                type: object
                properties:
                  short_url:
                    type: string
                    example: abc123
                  long_url:
                    type: string
                    example: https://perdu.com
                  created_at:
                    type: string
                    format: date-time
                  idLink:
                    type: integer
  /{url}:
    get:
      summary: Redirige vers l'URL longue et incrémente le compteur de visites
      parameters:
        - name: url
          in: path
          required: true
          schema:
            type: string
      responses:
        '302':
          description: Redirection vers l'URL longue
        '404':
          description: Lien non trouvé
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /status/{url}:
    get:
      summary: Récupère le nombre de visites pour un lien
      parameters:
        - name: url
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Nombre de visites du lien
          content:
            application/json:
              schema:
                type: object
                properties:
                  short_url:
                    type: string
                  visit:
                    type: integer
        '404':
          description: Lien non trouvé
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string